<?php

namespace app\admin\controller;

use app\BaseController;
use think\Controller;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub


        if(session('?adminInfo.rootId')){
            $this->redirect('admin/home/index');
        }

        $login = session('adminInfo.rootId');
        if (empty($login)){
            $url="{:url('admin/index/login')}";
            echo "<script>location.href=$url;</script>";
            exit(0);
        }

    }
}
